version: '3.7'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql_db
      DB_DATABASE: news_app_db
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mysql_db
    networks:
      - app


  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_app_db
    ports:
    - 3306:3306
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1

networks:
  app:
    driver: bridge